### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by shekshaa** [yjzhang96/Motion-ETR#2]
Hi,
Thank you for sharing the code.
Do you use `blur_gamma` folder or `blur` from GoPro dataset to generate aligned data?

**Comment by yjzhang96** [comment]
Thanks for your interest.
No, we use ```blur``` folder as our training data, as commonly used by former works.

**Comment by shekshaa** [comment]
Thanks. 
I just realized that you are following some previous work. So, as the sharp images are gamma-encoded, does your network also learn to apply gamma?
